##
## Used by run_analysis.R: Generates better (more readable) names out of the 
## names provided in the dataset. Returns a list of the same size as the list
## passed.
##
rename_features <- function(featureNames) {
    # Remove the prefix generated by R 
    featureNames = gsub("^X\\d+\\.","", featureNames)
    
    # Remove all Whitespace, Digits, Parentheses, Dashes, Commas...
    featureNames = gsub("\\s|\\d|\\(|\\)|\\-|\\.|\\,","", featureNames)
    
    # Frequency-domain variable names shall end with "Frequency"
    # Time-domain variable will have no suffix
    featureNames = gsub("^t(.*)","\\1", featureNames)
    featureNames = gsub("^f(.*)","\\1Frequency", featureNames)
    
    # Variable names shall begin with the type of variable they represent: 
    # Mean, Std (for Standard Deviation), Max, Min (Min and max do not 
    # effectively appear in the columns that are retained, but are provided 
    # here as an example of how this generic solution works)
    featureNames = gsub("(.*)mean(.*)","Mean\\1\\2", featureNames)
    featureNames = gsub("(.*)std(.*)","Std\\1\\2", featureNames)
    featureNames = gsub("(.*)min(.*)","Minimum\\1\\2", featureNames)
    featureNames = gsub("(.*)max(.*)","Maximum\\1\\2", featureNames)
    
    # Capitalize Activity and Subject. Using regexp here is a bit wasteful
    # but the idea is again to have a generic solution in case different
    # labels are used at a later point in time.
    featureNames = gsub("activity","Activity", featureNames)
    featureNames = gsub("subject","Subject", featureNames)
    
    # Use the names "Acceleration" and "AngularVelocity" instead of "Acc" 
    # and "Gyro", to better reflect what is being measured, as opposed to
    # where the data originated.
    featureNames = gsub("Acc","Acceleration", featureNames)
    featureNames = gsub("Gyro","AngularVelocity", featureNames)

    # Remove "Body" from the labels, the Gravity component can still
    # be differentiated by its differing names, the Body components are
    # all other variables. This shortens most variable names a bit.
    featureNames = gsub("Body","", featureNames)
        
    # Return the result
    featureNames
}